// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx3Ojik_LsJGgnFbPGWxYkou7HlbDf-dY',
    appId: '1:695654745781:web:eddab6e55af70afbeb20fc',
    messagingSenderId: '695654745781',
    projectId: 'frase-do-dia-app-46c9b',
    authDomain: 'frase-do-dia-app-46c9b.firebaseapp.com',
    storageBucket: 'frase-do-dia-app-46c9b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiTB9c9NhjewGoVzCDaSSfxeTXknyho_A',
    appId: '1:695654745781:android:fee2f9d52bd7289feb20fc',
    messagingSenderId: '695654745781',
    projectId: 'frase-do-dia-app-46c9b',
    storageBucket: 'frase-do-dia-app-46c9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0e4o5MyHkl-hQh5noogCrVw2xQZrZ7ac',
    appId: '1:695654745781:ios:40a1b33450f98106eb20fc',
    messagingSenderId: '695654745781',
    projectId: 'frase-do-dia-app-46c9b',
    storageBucket: 'frase-do-dia-app-46c9b.firebasestorage.app',
    iosBundleId: 'com.example.av6devsmoveis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0e4o5MyHkl-hQh5noogCrVw2xQZrZ7ac',
    appId: '1:695654745781:ios:40a1b33450f98106eb20fc',
    messagingSenderId: '695654745781',
    projectId: 'frase-do-dia-app-46c9b',
    storageBucket: 'frase-do-dia-app-46c9b.firebasestorage.app',
    iosBundleId: 'com.example.av6devsmoveis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx3Ojik_LsJGgnFbPGWxYkou7HlbDf-dY',
    appId: '1:695654745781:web:e0d47609508cb2b8eb20fc',
    messagingSenderId: '695654745781',
    projectId: 'frase-do-dia-app-46c9b',
    authDomain: 'frase-do-dia-app-46c9b.firebaseapp.com',
    storageBucket: 'frase-do-dia-app-46c9b.firebasestorage.app',
  );
}
